# 모든 스프링에 대한 설정하는 파일
# yml 파일은 json파일 형식으로 사용가능

# properties 파일 예시
# spring.datasource.data-username=@@@ 이런식으로 한줄 한줄 사용하는 단점이 있음
# yml 파일은 들여쓰기로 중복되는 코드를 줄일 수 있다. 
 
# spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
#    username: junho
#    password: 0000

server:
  port: 8080
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: junho
    password: Junho3407
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create #jpa 테이블 생성을 할 것인가 (테이블 생성후 데이터를 보존하고 싶다면 update로 변경!!)
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
        #컬럼을 생성할 때 이름 그대로 설정 
        # physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy 
        # 컬럼명을 memId -> mem_id 로 변경해서 컴럼명 생성
        use-new-id-generator-mappings: false #jpa의 기본 전략을 따를건지 설정
    show-sql: true # 콘솔 창에 jpa 실행 명령어를 보여주는 것 설정.
    properties:
      hibernate.format_sql: true #콘솔창에 실행문이 정렬되서 보여주는 것 설정

  jackson:
    serialization:
      fail-on-empty-beans: false